site_name: IR-NIYANTRAC (Indian Railways Native IoT based Yield Analysis Telemetry, Recording and Control) Guide

extra_css:
  - css/styles.css

extra_javascript:
  - js/script.js
  - https://www.googletagmanager.com/gtag/js?id=G-9DZ9LHMH53  #adding Google Analytics script here

extra:
  generator: false           #this for removing the copyright of mkdocs material theme in footer
  analytics:
    provider: google
    property: G-9DZ9LHMH53  #adding Google Analytics Property ID here
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: 1
        note: >-
          Thanks for your feedback!
      - icon: material/emoticon-sad-outline
        name: This page could be improved
        data: 0

theme:

  name: material

  # custom_dir: 'overrides'            # //not working

  logo: 'images/cdot_logo.png'

  features:
    - content.code.annotate 
    - content.code.copy
    # - navigation.footer             # //this for removal of horizontal navigation at footer
    - content.footnote.tooltips
    - navigation.indexes
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    # - toc.integrate                # //this for getting toc 

  language: en


  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime  


plugins:
  - search


markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list


copyright: |
  &copy; 2024 <a href="https://github.com/pootrivs"  target="_blank" rel="noopener">Centre for Development of Telematics</a>


nav:
  - Home: 
    - 'index.md'
    - About CCSP: 
      - 'irniyantrac/ccsp/index.md'
    - About IR-NIYANTRAC:  
      - 'irniyantrac/index.md'
    - IR-NIYANTRAC Onboarding: 
      - 'irniyantrac/onboarding/index.md'
    - OneM2M-AppId Registration:
      - 'irniyantrac/oneM2MAppIdRegistration/index.md' 
  - IR-NIYANTRAC Messages:
    - 'irniyantracMessages/index.md'
    - Containers and Subscriptions Payloads:   
        - 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
    - IFD Message Payloads: 
        - 'irniyantracMessages/ifdMessagePayloads/index.md'
    - Cloud/IR-NIYANTRAC Notification Payloads:
        - 'irniyantracMessages/cloudIrniyantracNotificationPayloads/index.md'
    - IR-NIYANTRAC Common Errors and Resolution: 
        - 'irniyantracMessages/irniyantracCommonErrorsResolutions/index.md'  
  # - Useful Vedios:
  #   - 'usefulVedios/index.md'















































##################################################################################


# - Monitoring Container: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Monitoring Container Subscription: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Monitoring Buffer Container: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Monitoring Buffer Container Subscription: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Alert Container: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Alert Container Subscription: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Alert Buffer Container: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Alert Buffer Container Subscription: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Acknowledgement Container: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Acknowledgement Container Subscription: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Acknowledgement Buffer Container: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Acknowledgement Buffer Container Subscription: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Device Connect Container: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'
        # - Device Connect Container Subscription: 'irniyantracMessages/containersAndSubscriptionsPayloads/index.md'




# - Alerts: 'irniyantracMessages/ifdMessagePayloads/alerts.md'
        # - Connect Time/Sync: 'irniyantracMessages/ifdMessagePayloads/connectTimeSync.md'
        # - Control Subscribe Ack: 'irniyantracMessages/ifdMessagePayloads/controlSubscribeAck.md'
        # - External Device Monitoring: 'irniyantracMessages/ifdMessagePayloads/externalDeviceMonitoring.md'
        # - Get Existing Schedule List Response: 'irniyantracMessages/ifdMessagePayloads/getExistingScheduleListResponse.md'
        # - Monitoring: 'irniyantracMessages/ifdMessagePayloads/monitoring.md'
        # - Schedule Executed: 'irniyantracMessages/ifdMessagePayloads/scheduleExecuted.md'
        # - Schedule Publish Response: 'irniyantracMessages/ifdMessagePayloads/schedulePublishResponse.md'



# - Connect Time/Sync Ack: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/connectTimeSyncAck.md'
        # - Connect Time/Sync Ack Response: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/connectTimeSyncAckResponse.md'
        # - Sensor Values Monitoring: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/sensorValuesMonitoring.md'
        # - Control Publish Operation: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/controlPublishOperation.md'
        # - Control Publish Sensor Calibration: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/controlPublishSensorCalibration.md'
        # - Schedule Publish: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/schedulePublish.md'
        # - Reset Schedule: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/resetSchedule.md'
        # - Reset Schedule Acknowledgement: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/resetScheduleAcknowledge.md'
        # - Get Existing Schedule List: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/getExistingScheduleList.md'
        # - Publish Rule: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/publishRule.md'
        # - Rule Executed Response: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/ruleExecutedResponse.md'
        # - Reset Rule: 'irniyantracMessages/cloudIrniyantracNotificationPayloads/resetRule.md'


###################################################################################


