site_name: CCSP docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list


copyright: |
  &copy; 2024 <a href="https://github.com/pootrivs"  target="_blank" rel="noopener">Poornima Shandilya</a>


nav:
  - Home: 
    - 'index.md'
  - IRNIYANTRAC:
    - 'irniyantrac/index.md'
    - An Introduction to IRNIYANTRAC: 'irniyantrac/irniyantracIntroduction.md'
    -  IRNIYANTRAC onboarding steps: 'irniyantrac/irniyantracOnboarding.md'
    -  IRNIYANTRAC Resource Hierarchy: 'irniyantrac/irniyantracResourceHierarchy.md'
    -  IRNIYANTRAC Messages:
        - Resource Hierarchy Creation: 'irniyantrac/irniyantracMsgs/irniyantracResourceHierarchyCreation.md'  
        - Monitoring Messages: 'irniyantrac/irniyantracMsgs/irniyantracMonitoringMessages.md'
        - Control commands:   'irniyantrac/irniyantracMsgs/irniyantracControlMessages.md'  
    -  IRNIYANTRAC Common Errors and Resolution: 'irniyantrac/irniyantracCommonErrors.md'    
  